# Generated by Django 4.2.1 on 2023-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_posts_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
