# Generated by Django 4.2.1 on 2023-09-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '__first__'),
        ('community', '0003_posts_downvotes_posts_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='posts',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(choices=[(1, 'UpVote'), (0, 'None'), (-1, 'DownVote')], default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.users')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
