# Generated by Django 4.2.1 on 2023-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verified_as',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Psychologist'), (2, 'Psychiatrist'), (3, 'NGO/Indepent Body')], default=0),
        ),
    ]
