# Generated by Django 4.2.1 on 2023-09-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_users_verified_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verified_as',
            field=models.TextField(choices=[('user', 'User'), ('psychologist', 'Psychologist'), ('psychiatrist', 'Psychiatrist'), ('ngo', 'NGO/Indepent Body')], default='user'),
        ),
    ]
