# Generated by Django 4.2.1 on 2023-09-17 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0003_alter_users_verified_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_in_years', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('verified_as', models.TextField(choices=[('psychologist', 'Psychologist'), ('psychiatrist', 'Psychiatrist')])),
                ('no_of_ratings', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('charge', models.PositiveIntegerField(default=0)),
                ('appointment_duration_hours', models.PositiveIntegerField(default=1)),
                ('email', models.OneToOneField(limit_choices_to=models.Q(('verified_as', 'psychologist'), ('verified_as', 'psychiatrist'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='authenticator.users')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(choices=[('user', 'user'), ('professional', 'professional')])),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.appointments')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.professionals'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.users'),
        ),
    ]
